name: Build, test and publish Python package to PyPI and TestPyPI

on: 
  pull_request:
    branches:
      - "main"
      - "maintain/**"
      - "master"
      - "hotfix**"
      - "**fix**"
      - "release/**"
    types:
      - closed
  
jobs:
  build-n-publish:
    name: Build and publish to PyPI and TestPyPI for Python ${{ matrix.py }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macosx]
        py: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]
        
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}
      - name: Install pypa/build
        run: >-
          python3 -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python3 -m
          build
          --sdist
          --wheel
          --outdir dist/
          .
      - name: Run tests
        run: >-
          python3 -m pip install pytest
          pytest tests
      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.cfg') }}-${{ hashFiles('requirements.txt') }}
      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TEST_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
      

